### ISSUE TITLE
Ajout - Repo PR_TEMPLATE

### ISSUE THREAD

**Issue by WinstonBlewUp** [CHANG-Toma/ProjetFinalGit#29]
## Description

Ajout du répertoire PULL_REQUEST_TEMPLATE

## Comportement Attendu

Faciliter la reconnaissance par git du template de pull request -> faire fonctionner le templating

## Comportement Actuel

Ca marche pas pour le moment

## Informations Complémentaires

En vue du merge ça devrait fonctionner si je suis pas trop mauvais

**Comment by CHANG-Toma** [comment]
et bah noon toujours pas xD

**Comment by CHANG-Toma** [comment]
du coup, c'est good il fallait jute le mettre directement dans le dossier .github, en minuscule..

je le savais pas non plus...
